Layout for fragment search
olgaportnova/practicum-android-diploma pull request #15
Opened 2023-10-30 19:47 UTC by olgaportnova

Привет! 
Посмотрите, плиз, фрагмент для экрана поиска. 
Сделала ресайкл + плейсхолдеры (для них загрузила три картинки для трех возможных стейтов). 
У меня, наверное, уже замылился взгляд пока я делала, поэтому, буду рада вашим комментариям :) 

p.s. из того, что мне кажется, можно и нужно лучше реализовать, но что-то я пока не сообразила как: 
- высота самого поля edit text (у меня сейчас фикс значение, но боюсь, что при тесте на большом шрифте что-то обрежется) 
- margin top для картинки placeholder-а у меня тоже фикс значение, как думаете насколько это норм?

2023-10-31 11:47 UTC, TanyaRul requested changes
Также есть такой критерий в требованиях: Если поле ввода поискового запроса непустое, то видна кнопка для его очистки. Нажатие на эту кнопку удаляет введённый текст. Не увидела в вёрстке какого-либо элемента для этого. Или как-то по другому будет меняться иконка?

2023-10-31 11:47 UTC, TanyaRul commented on app/src/main/res/values/styles.xml
> +        <item name="android:layout_marginTop">151dp</item>
Здесь можно попробовать не указывать marginTop, а сделать привязку элемента с картинкой app:layout_constraintBottom_toBottomOf="parent"

2023-10-31 11:47 UTC, TanyaRul commented on app/src/main/res/values/styles.xml
> +        <item name="android:layout_marginVertical">@dimen/placeholder_text_margin_horizontal</item>
Кажется здесь должен быть просто marginTop=16dp

2023-10-31 11:47 UTC, TanyaRul commented on app/src/main/res/values/styles.xml
> +        <item name="android:layout_height">48dp</item>
В критериях оценки у нас есть такой пункт: Значения цвета, отступов, размеров текста и строковые константы вынесены в соответствующие файлы ресурсной директории values. Думаю, лучше сразу выносить все значения, чтобы потом не переделывать.

2023-10-31 12:00 UTC, TanyaRul commented on app/src/main/res/values/styles.xml
> +    <style name="edit_text">
По макету в этом поле нужно цветной курсор сделать

2023-10-31 18:50 UTC, x-mike commented on app/src/main/res/drawable-mdpi/placeholder_no_internet.png
Данный холдер должен быть показан при остуствии подключения к интернету и дополнительно, должна быть надпись "Нет интернета". Не увидел, где в версте есть реализация данного стейта. Или ты в дальнейшем это планировала реализовать по другому, через фрагмент ??

2023-10-31 18:52 UTC, x-mike commented on app/src/main/res/drawable-mdpi/placeholder_start_of_search.png
Данный холдер должен быть показан первым при закрузке экрана search, но его я тоже не увидел в верстке.

2023-10-31 18:57 UTC, x-mike commented on app/src/main/res/drawable-xxhdpi/placeholder_start_of_search.png
Здорово, что давлены ресурсы для разных размеров экранов!

2023-10-31 19:30 UTC, x-mike commented on app/src/main/res/layout/fragment_search.xml
> +        app:layout_gravity="center_vertical"
Наверное, данную строчку нужно заменить на android:layout_gravity="center_vertical". Т.к. без этого не собирается проект.

2023-10-31 20:21 UTC, x-mike commented on app/src/main/res/layout/fragment_search.xml
>          app:title="@string/search_fragment_title"
Стиль заголовка не соотвествует стилю в фигме, неопходимо переопредить стиль title.
![Uploading 2023-10-31_23-02.png…]()

2023-10-31 20:26 UTC, x-mike commented on app/src/main/res/layout/fragment_search.xml
> +        app:titleTextColor="@color/black"
Цвет текста по фигме #1A1B22, но не black.

2023-10-31 20:40 UTC, x-mike commented on app/src/main/res/values/styles.xml
> +    <style name="edit_text">
Согласен =)

2023-10-31 20:43 UTC, x-mike commented on app/src/main/res/values/styles.xml
> +        <item name="android:textSize">16sp</item>
Размер <item name="android:textSize">16sp</item> лучше вынести в отдлеьный dimens ресурс, он повторяется.

2023-10-31 21:14 UTC, x-mike commented on app/src/main/res/layout/fragment_search.xml
> +        tools:src="@drawable/placeholder_empty_result"
Не понятно для чего тут ресурс указан как tools ( tools:src="@drawable/placeholder_empty_result") он должен быть android:src так должен быть виден на экране.

2023-10-31 21:15 UTC, x-mike commented on app/src/main/res/layout/fragment_search.xml
> +        tools:text="@string/no_search_result"
Тоже самое ресурс tools, а должен быть виден на экране: android:text

2023-10-31 21:19 UTC, x-mike commented on app/src/main/res/menu/search_vacancies_menu.xml
> +        android:icon="@drawable/ic_filters"
Для иконки ic_filters должен быть добавлен shape, т.к. выделенная иконка имеет бэкграунд.
![2023-11-01_00-19](https://github.com/olgaportnova/practicum-android-diploma/assets/118683285/1d274c4a-9078-4fc5-8a90-2129dbd8cc9e)

2023-10-31 21:34 UTC, x-mike commented on app/src/main/res/values/colors.xml
Комментарий оставляю к цветам, т.к. он относится к ночной теме и требует проработки цвета текста и иконки. В соотвествии с скринами:
![2023-11-01_00-22](https://github.com/olgaportnova/practicum-android-diploma/assets/118683285/dea5329d-e75d-459c-b44a-80efea9ac4c4)
![2023-11-01_00-22_1](https://github.com/olgaportnova/practicum-android-diploma/assets/118683285/ad50b363-6503-4f0a-9960-47b43cfff460)
Дополнительно неверный цвет бэкграунда. Он у тебя black, а должен быть #1A1B22

2023-10-31 21:39 UTC, x-mike commented on app/src/main/res/values/strings.xml
> +    <string name="found_vacancies_count">Найдено %1$d вакансий</string>
Не понятно где используется данный ресурс    <string name="found_vacancies_count">Найдено %1$d вакансий</string>

2023-10-31 21:46 UTC, x-mike requested changes
Я думаю нужно быть внимательней, много несоответсвий по верстке. Также желательно запускать проект у себя на ПК, чтобы удоствориться, что все работает корректно.

2023-11-01 06:24 UTC, olgaportnova commented on app/src/main/res/drawable-mdpi/placeholder_no_internet.png
я планировала, что мы будет показывать картинки и текст плейсхолдера или же recycle в зависимости от state
те я сделала сами view, куда будем устанавливать необходимые картинки, текст

2023-11-01 06:25 UTC, olgaportnova commented on app/src/main/res/drawable-mdpi/placeholder_start_of_search.png
аналогично, как и прошлый ответ, мы его установим из state

2023-11-01 06:27 UTC, olgaportnova commented on app/src/main/res/layout/fragment_search.xml
> +        tools:src="@drawable/placeholder_empty_result"
по логике со стейтами он не должен быть виден на экране, он tools чтобы сейчас было наглядней

2023-11-01 06:28 UTC, olgaportnova commented on app/src/main/res/layout/fragment_search.xml
> +        tools:text="@string/no_search_result"
по логике со стейтами он не должен быть виден на экране, он tools чтобы сейчас было наглядней

2023-11-01 06:31 UTC, olgaportnova commented on app/src/main/res/values/styles.xml
> +        <item name="android:layout_height">56dp</item>
исправила, спасибо

2023-11-01 06:35 UTC, olgaportnova commented on app/src/main/res/values/styles.xml
> +        <item name="android:textSize">16sp</item>
исправила

2023-11-01 06:54 UTC, olgaportnova commented on app/src/main/res/layout/fragment_search.xml
> +        app:layout_gravity="center_vertical"
исправила, спасибо

2023-11-01 06:56 UTC, olgaportnova commented on app/src/main/res/values/styles.xml
> +    <style name="edit_text">
исправила

2023-11-01 07:14 UTC, olgaportnova commented on app/src/main/res/values/styles.xml
> +        <item name="android:layout_marginVertical">@dimen/placeholder_text_margin_horizontal</item>
исправила

2023-11-01 07:18 UTC, olgaportnova commented on app/src/main/res/values/styles.xml
> +        <item name="android:layout_marginTop">151dp</item>
точно! спасибо

2023-11-01 07:22 UTC, olgaportnova commented on app/src/main/res/layout/fragment_search.xml
> +        app:titleTextColor="@color/black"
исправила

2023-11-01 07:25 UTC, olgaportnova commented on app/src/main/res/values/styles.xml
> +        <item name="android:layout_marginTop">@dimen/recycle_whole_margin_top</item>
исправила на 8
да, вот при прокрутке не знаю как реализовать, чтобы recycle заезжает под cообщение 
наверное, проще будет понять, когда у нас будет заполненный recycle

2023-11-01 07:28 UTC, olgaportnova commented on app/src/main/res/values/styles.xml
> +        <item name="android:textSize">16sp</item>
вынесла

2023-11-01 07:30 UTC, olgaportnova commented on app/src/main/res/values/styles.xml
> +        <item name="android:layout_height">48dp</item>
вынесла

2023-11-01 08:05 UTC, olgaportnova commented on app/src/main/res/menu/search_vacancies_menu.xml
> +        android:icon="@drawable/ic_filters"
я добавила новый drawable, который будет с фоном, и менять icon по факту выбран ли фильтр или нет 
по-другому в toolbar не вижу возможности реализовать

2023-11-01 08:17 UTC, x-mike commented on app/src/main/res/drawable-mdpi/placeholder_no_internet.png
Ок, понятно.

2023-11-01 08:18 UTC, x-mike commented on app/src/main/res/layout/fragment_search.xml
> +        tools:src="@drawable/placeholder_empty_result"
Ок.

2023-11-01 08:18 UTC, x-mike commented on app/src/main/res/layout/fragment_search.xml
> +        tools:text="@string/no_search_result"
Ок.

2023-11-01 08:19 UTC, x-mike commented on app/src/main/res/menu/search_vacancies_menu.xml
> +        android:icon="@drawable/ic_filters"
Хорошо. Думаю такой варинат пока подойдет.

2023-11-01 08:43 UTC, olgaportnova commented on app/src/main/res/layout/fragment_search.xml
>          app:title="@string/search_fragment_title"
добавила

2023-11-01 10:21 UTC, olgaportnova commented on app/src/main/res/layout/fragment_search.xml
> +        style="@style/edit_text" />
кол-во строк ограничила, а длина обрезается автоматически перед лупой, тк это drawableEnd

2023-11-01 10:33 UTC, olgaportnova commented
@TanyaRul 
по поводу крестика для очистки текста, я добавила этот icon, но думала подставлять его в drawableEnd после проверки пустая ли строка уже в коде. 
Или как то по-другому лучше реализовать?

2023-11-01 11:51 UTC, TanyaRul commented
> @TanyaRul по поводу крестика для очистки текста, я добавила этот icon, но думала подставлять его в drawableEnd после проверки пустая ли строка уже в коде. Или как то по-другому лучше реализовать?
Да, хорошо, сделаем так.

2023-11-01 11:54 UTC, TanyaRul approved these changes
Всё хорошо, только один момент не увидела в первый раз: когда открывается клавиатура должна скрываться нижняя панель навигации, сейчас она оастается. По поводу кнопки очистки давай сделаем по твоей задумке.

2023-11-01 11:58 UTC, olgaportnova commented
@TanyaRul добавила в манифест про клавиатуру и панель навигации

2023-11-01 15:32 UTC, x-mike approved these changes
После внесния изменений не забудить решить, локально, конфликты.

2023-11-01 19:31 UTC, merged