Customize layout for WorkPlace fragment
olgaportnova/practicum-android-diploma pull request #41
Opened 2023-11-04 13:20 UTC by OlegQt

Изменил Layout Фрагмента в соответствие с макетом
Сделал программное изменение заголовков "страна" и "регион" в зависимости от выбора или удаления данных в модели
Видимость кнопки "Выбрать" рассчитывается внутри viewModel
Так же доделал функционал по моментальному выходу с фрагментов выбора страны и региона после выбора искомой area

2023-11-04 15:46 UTC, x-mike commented on app/src/main/java/ru/practicum/android/diploma/filter/data/impl/dto/VacancyResponse.kt
> +)
Подскажи, это тестовый класс или он будет использоваться в фильтрах ?? Просто не припомню где там нужны вакансии ??

2023-11-04 15:50 UTC, OlegQt commented on app/src/main/java/ru/practicum/android/diploma/filter/data/impl/dto/VacancyResponse.kt
> +)
Да, это тестовый.  Забыл удалить

2023-11-04 17:31 UTC, TanyaRul requested changes

2023-11-04 17:31 UTC, TanyaRul commented on app/src/main/res/layout/fragment_work_place.xml
> +            android:text="@string/work_place_country_title"
Мне кажется здесь и в названии региона нужно обрезать строку, потому что сейчас получается так 
![countryregion](https://github.com/olgaportnova/practicum-android-diploma/assets/118722638/22563fb7-1e4c-40b5-ae1c-676deee43608)

2023-11-04 18:29 UTC, OlegQt commented on app/src/main/res/layout/fragment_work_place.xml
> +        app:title="@string/work_place_fragment_title" />
Выполнил, кроме как подвинуть заголовок левее. У него margin и так нулевой и padding тоже

2023-11-04 18:30 UTC, OlegQt commented on app/src/main/res/layout/fragment_work_place.xml
> +    <LinearLayout
done

2023-11-04 18:34 UTC, OlegQt commented on app/src/main/res/layout/fragment_work_place.xml
> +            android:textSize="16sp" />
done

2023-11-04 18:40 UTC, OlegQt commented on app/src/main/res/layout/fragment_work_place.xml
> +            android:text="@string/work_place_country_title"
Done

2023-11-04 18:51 UTC, TanyaRul commented on app/src/main/java/ru/practicum/android/diploma/filter/presentation/fragment/WorkPlace.kt
> +        binding.txtChooseDistrict.text = getString(R.string.work_place_country_title)
Здесь выводится заголовок "Страна", а должен быть "Регион"

2023-11-04 20:19 UTC, TanyaRul approved these changes

2023-11-04 21:49 UTC, OlegQt commented on app/src/main/java/ru/practicum/android/diploma/filter/presentation/fragment/WorkPlace.kt
> +        binding.txtChooseDistrict.text = getString(R.string.work_place_country_title)
Done

2023-11-05 09:29 UTC, TanyaRul approved these changes

2023-11-05 11:22 UTC, merged